export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function LoginLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="h-full bg-white">
			<body className="h-full">{children}</body>
		</html>
	);
}
