"use client";
import "./globals.css";
import { RootStyleRegistry } from "./antd";
import { store } from "@/store";
import { Provider } from "react-redux";

// export const metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<RootStyleRegistry>
					<Provider store={store}>{children}</Provider>{" "}
				</RootStyleRegistry>
			</body>
		</html>
	);
}
